global proc ParentGroup()
{
    string $sels[] = `ls -sl`;
    
    for ($sel in $sels)
    {
        string $parent[] = `listRelatives -parent -fullPath $sel`;
        
        string $grp = `group -empty -name ($sel + "_Grp")`;
        matchTransform $grp $sel;
        parent $sel $grp;
        
        
        if (size($parent) >0 )
            print ($grp + "_" + $parent[0]);
            parent $grp $parent[0];
    }
}
ParentGroup();